export default Object.freeze({
  SPLASH_SCREEN: 'SplashScreen',
  WELCOME_SCREEN: 'WelcomeScreen',
  LOGIN_SCREEN: 'LoginScreen',
  CREATE_ACCOUNT_SCREEN: 'CreateAccountScreen',
  VERIFY_PHONE_NUMBER_SCREEN: 'VerifyPhoneNumberScreen',
  OTP_SCREEN: 'OtpScreen',
  HOME_SCREEN: 'HomeScreen',
  RECYCLE_SCREEN: 'RecycleScreen',
  SCHEDULE_SCREEN: 'ScheduleScreen',
  APPOINTMENT_SCREEN: 'AppointmentScreen',
  HISTORY_SCREEN: 'HistoryScreen',
  PROFILE_SCREEN: 'ProfileScreen',
  HOME: 'home',
  COLLECTOR_QUESTIONNAIRE: 'CollectorQuestionnaire',
  PICKUP_APPOINTMENT_SCREEN: 'PickupAppointmentScreen',
  FORGOT_PASSWORD: 'ForgotPassword',
});
